### ISSUE TITLE
Greeting and starting the reviewing process 👋 

### ISSUE THREAD

**Issue by hoangnguyen92dn** [hm-tamim/nimble-survey#1]
Hello Tamim,

Nice to e-meet you 👋  and thanks for your effort on this submission. My name is Huey - an Android Developer at Nimble and I would like to conduct the feedback via Issue tickets regarding your performance here.

Keep in mind, this is a bidirectional process, so we would love to hear back from you as well, so please don’t hesitate to raise your question/correction in case we missed anything.

If we’re aligned on any issue here and you’d like to correct them, please go ahead and open a Pull Request per fix, merge it when you feel confident and we will follow up on those fixes 😇

**Comment by hm-tamim** [comment]
Hi Huey, nice to e-meet you too. I will be making changes based on your feedbacks as soon as possible. Looking forward our the collaboration.

**Comment by hoangnguyen92dn** [comment]
@hm-tamim You can close the issue once resolved. I will follow up on your update then.

**Comment by hm-tamim** [comment]
@hoangnguyen92dn got it. Thanks

**Comment by hoangnguyen92dn** [comment]
@hm-tamim Sorry for the late response. We will review the updates and discuss with our team to finalize the evaluation ✌️

**Comment by hm-tamim** [comment]
Hi @hoangnguyen92dn, no problem at all. Eagerly waiting for the update 😄
