### ISSUE TITLE
There are some issues in the API handling

### ISSUE THREAD

**Issue by hoangnguyen92dn** [hm-tamim/nimble-survey#3]
- [x] From what I see on your implementation, there is a condition to validate the success response repeatedly on different API responses; I'd suggest handling the API response with the function/extension for usage to avoid duplication.

https://github.com/hm-tamim/nimble-survey/blob/6b084556f855e13bd07da436040cab63eeed6832/data/src/main/java/co/nimblehq/survey/data/repositoryimpl/SurveyRepository.kt#L18-L33

https://github.com/hm-tamim/nimble-survey/blob/6b084556f855e13bd07da436040cab63eeed6832/data/src/main/java/co/nimblehq/survey/data/repositoryimpl/AuthRepository.kt#L30-L42

https://github.com/hm-tamim/nimble-survey/blob/6b084556f855e13bd07da436040cab63eeed6832/data/src/main/java/co/nimblehq/survey/data/repositoryimpl/AuthRepository.kt#L54-L66

- [ ] I am curious why you are using Hilt to manage instances but still need the "holder" here? 🤔 It violates the DI pattern by exposing the API service’s instance in the `ApiServiceHolder`

https://github.com/hm-tamim/nimble-survey/blob/6b084556f855e13bd07da436040cab63eeed6832/data/src/main/java/co/nimblehq/survey/data/service/ApiServiceHolder.kt#L5-L16

- [x] #13

https://github.com/hm-tamim/nimble-survey/blob/6b084556f855e13bd07da436040cab63eeed6832/data/src/main/java/co/nimblehq/survey/data/service/AuthenticationRefreshToken.kt#L54-L59

**Comment by hm-tamim** [comment]
@hoangnguyen92dn 

**ApiServiceHolder** was used to prevent dependency cycle. It simply keeps the instance of ApiService, every time when it's initialized by Hilt. Tried Lazy, didn't seem to work.

https://github.com/hm-tamim/nimble-survey/blob/6ec84fab58d05f01ff5721440c46f2b2ec203f93/app/src/main/java/co/nimblehq/survey/di/modules/RetrofitModule.kt#L47

![Screenshot 2022-04-08 161545](https://user-images.githubusercontent.com/43744334/162421507-76b66425-adf8-4e77-a59b-d6ae76bbad68.png)

In my previous companies, they handled it like this. Do you have any better approach?

**Comment by hoangnguyen92dn** [comment]
@hm-tamim Technically, it comes from your implementation to manage dependencies and coupled between module/layer. The `AuthenticationRefreshToken` depends on API Service to send requests to the API endpoint, why don't we call the API request through Repository instead, since the data source should be accessed via Repository class? 🤔

**Comment by hm-tamim** [comment]
But the Repository also depends on the ApiService(injected from constructor), it causes the same dependency cycle issue. 

https://github.com/hm-tamim/nimble-survey/blob/6ec84fab58d05f01ff5721440c46f2b2ec203f93/data/src/main/java/co/nimblehq/survey/data/repositoryimpl/AuthRepository.kt#L16-L19

**Comment by hm-tamim** [comment]
Hi @hoangnguyen92dn, 

Fixed the 1st and 3rd task you mentioned. App now has a response handler and a mapper to handle API calls automatically. Created PR.

**Comment by hoangnguyen92dn** [comment]
> But the Repository also depends on the ApiService(injected from constructor), it causes the same dependency cycle issue.

@hm-tamim Got it. With the refreshing access token, I'd suggest having 2 different API Services, the first one for Login and the second one for the refreshing access token, you can manage instances by Hilt for usage.

**Comment by hm-tamim** [comment]
@hoangnguyen92dn Your suggested implementation is done and pushed. 

0bded74aef27aa0f99a886a128cce6bcae0cf188

**Comment by hoangnguyen92dn** [comment]
@hm-tamim Take your time to resolve the remaining issues. Don't hesitate to lemme know if you need any clarification on the issues or the timeframe for the code review process.
I am off for the weekend and will follow up on the updates next Monday 🏖️  Enjoy your weekend and happy coding ✌️

**Comment by hm-tamim** [comment]
Thank you. Enjoy the weekend 🥳 I will do some coding in meantime, haha. It's fun! Btw, do I have time till Sunday night? 

As I mentioned previously, I couldn't work on the assignment in first 4 days due to home shifting, else it would have been more polished.
