### ISSUE TITLE
Extract hardcoded text to string resource

### ISSUE THREAD

**Issue by hoangnguyen92dn** [hm-tamim/nimble-survey#6]
It would be better by define these texts in string resource instead. For example:

https://github.com/hm-tamim/nimble-survey/blob/6b084556f855e13bd07da436040cab63eeed6832/app/src/main/java/co/nimblehq/survey/ui/screens/MainActivity.kt#L44-L50

https://github.com/hm-tamim/nimble-survey/blob/6b084556f855e13bd07da436040cab63eeed6832/app/src/main/java/co/nimblehq/survey/ui/screens/home/HomeFragment.kt#L72-L79

**Comment by hm-tamim** [comment]
Hi, it's fixed d31431947e9e56e208c8f8b503211eff7bc8c3b6
